apiVersion: v1
appVersion: "20.3.1"
description: Report Kubernetes cluster and pod resource requests vs usage and generate static HTML
name: kube-resource-report
version: 0.3.0
home: https://github.com/hjacobs/kube-resource-report.git
